GET http://localhost:3000/api/me 
Content-Type: application/json
Authorization: Bearer ce484578-9daf-4e17-bed8-116a554c534f

###

DELETE http://localhost:3000/api/testing/reset
Content-Type: application/json
Authorization: Bearer ce484578-9daf-4e17-bed8-116a554c534f

###

POST http://localhost:3000/api/testing/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer ce484578-9daf-4e17-bed8-116a554c534f

{
  "username": "juanRulfo",
  "name": "Juan Rulfo",
  "password": "LlanoLlamas.1953"
}

###
